### ISSUE TITLE
ZeroDivisionError 

### ISSUE THREAD

**Issue by alagos** [cltorresfe/members#94]
@cltorresfe 

```
ZeroDivisionError (divided by 0):

app/models/member.rb:82:in `/'
app/models/member.rb:82:in `block in by_range'
app/models/member.rb:78:in `each'
app/models/member.rb:78:in `by_range'
app/controllers/main_controller.rb:9:in `index'
```

**Comment by cltorresfe** [comment]
Fixed. PR #95
